version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - lll
    - nlreturn
    - wsl
  settings:
    depguard:
      rules:
        deprecated:
          deny:
            - pkg: github.com/aws/aws-sdk-go/aws
              desc: use "github.com/aws/aws-sdk-go-v2/aws"
    tagliatelle:
      case:
        rules:
          json: goCamel
          yaml: goCamel
    revive:
      enable-all-rules: true
      rules:
        - name: package-comments
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: add-constant
          arguments:
            - allowInts: 0,1,2
              allowStrs: '""'
          exclude:
            - TEST
        - name: cognitive-complexity
          exclude:
            - TEST
        - name: function-length
          exclude:
            - TEST
    varnamelen:
      ignore-decls:
        - T any
        - i int
        - ok bool
        - r *http.Request
        - r io.Reader
        - ts *httptest.Server
        - w http.ResponseWriter
        - w io.Writer
  exclusions:
    rules:
      - linters:
          - err113
          - funlen
        path: _test\.go
      - linters:
          - varnamelen
        path: _test\.go$
        text: variable name 'tt' is too short for the scope of its usage
formatters:
  enable:
    - goimports
    - gci
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - blank
        - dot
        - alias
        - localmodule
