linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - gofumpt
    - nlreturn
    - wsl
    # deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

linters-settings:
  tagliatelle:
    case:
      rules:
        json: goCamel
        yaml: goCamel
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - ok bool
      - r *http.Request
      - r io.Reader
      - ts *httptest.Server
      - w http.ResponseWriter
      - w io.Writer
