" Generated by vim-plug
" Mon 03 Apr 2023 09:53:03 AM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = 'fbae1bc1937ce69fa80b4b32d178ce666fd5c07c'
silent! let g:plugs['ctrlp.vim'].commit = '8b4a9523632049b3b373de1233bef346073b8982'
silent! let g:plugs['lowercase-dockerfile'].commit = '335feba0805d02be0a414d790b8094ee54d8456c'
silent! let g:plugs['quick-scope'].commit = 'a147fe0b180479249a6770eac332e2cd8f35b673'
silent! let g:plugs['supertab'].commit = 'f0093ae12a9115498f887199809a6114659fc858'
silent! let g:plugs['tagbar'].commit = 'af3ce7c3cec81f2852bdb0a0651d2485fcd01214'
silent! let g:plugs['ultisnips'].commit = '0ad238b1910d447476b2d98f593322c1cdb71285'
silent! let g:plugs['vim-airline'].commit = 'a532fed72ace069e61c0132125b728316f9abd3c'
silent! let g:plugs['vim-airline-themes'].commit = 'dd81554c2231e438f6d0e8056ea38fd0e80ac02a'
silent! let g:plugs['vim-cterm'].commit = 'b33c2a9225c53f90fb8d543daecfc66b5ce32e72'
silent! let g:plugs['vim-gitgutter'].commit = '44dbd57dd19e8ec58b2a50c787c8ae7bb231c145'
silent! let g:plugs['vim-go'].commit = '23cc4bca2f586c8c2f7d2cb78bbbfec4b7361763'
silent! let g:plugs['vim-go-snippets'].commit = 'b5eeef0f944b9d473886a8e8bcf2ca44c174cfb3'
silent! let g:plugs['vim-snippets'].commit = 'c7e61b73a546c9dd0525cd158cc1613bb48e414a'

PlugUpdate!

