" Generated by vim-plug
" Wed 21 Oct 2020 10:39:25 AM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = '08295ce17405cb5f6c80d2f726262493bfd21210'
silent! let g:plugs['ctrlp.vim'].commit = 'd93d97813dc839ef0782302a0debd7c4877f09f3'
silent! let g:plugs['molokai'].commit = '98c1c80661bb977fc340d0ac9cedd63cd91ec6f6'
silent! let g:plugs['supertab'].commit = '40fe711e088e2ab346738233dd5adbb1be355172'
silent! let g:plugs['ultisnips'].commit = '7941f98337564d4e86cf2b7467b64def4d212794'
silent! let g:plugs['vim-airline'].commit = '27b52acee77ccd5972cc385bb5017141c14bb120'
silent! let g:plugs['vim-brightest'].commit = '717682eda87a4b9a19720b01ef5b09c339e3412c'
silent! let g:plugs['vim-color'].commit = 'fd76773180ddadcfcc56f957182c5ab2a4f58bb1'
silent! let g:plugs['vim-gitgutter'].commit = 'ea79bc01c2efc84cf8e71fbe5fd8adbf4242739d'
silent! let g:plugs['vim-go'].commit = '9b9b527d61a6fe10a6d0c618cc0dd113b6aa7690'
silent! let g:plugs['vim-go-snippets'].commit = '3f43b5e81f695cd236d18d0e020ab47338c6f12e'
silent! let g:plugs['vim-snippets'].commit = '791c72d53399c7db9ec5a19922efee15d8f5a94b'

PlugUpdate!

